site_name: Shopware 6 Plugin Dokumentation von moori
theme:
    name: 'material'
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          accent: light green
          primary: deep orange
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
plugins:
    - i18n:
          default_language: de
          languages:
              de: Deutsch
              en: English
          nav_translations:
              de:
                  Documentation: App Dokumentation
                  MoorlCms: Erlebniswelten CMS Apps
                  MoorlFormBuilder: Formular Baukasten
                  Extensions: Erweiterungen
                  MoorlSignIn: Login mit Facebook, Google usw
                  MoorlMagazine: Blog mit Wordpress Import
                  MoorlMerchantFinder: Händler- und Filialiensuche
                  MoorlCreator: Öffentliche Profile
                  Imprint: Impressum
              en:
                  Documentation: App Documentation
                  MoorlCms: Shopping worlds CMS Apps
                  MoorlFormBuilder: Form Builder
                  Extensions: Extensions
                  MoorlSignIn: Sign-In with Facebook, Google etc
                  MoorlMagazine: Blog with Wordpress Import
                  MoorlMerchantFinder: Merchant- and Storefinder
                  MoorlCreator: Public profiles
                  Imprint: Imprint
    - search
docs_dir: 'docs-source'
site_dir: 'docs-html'
site_url: 'https://docs.moori.net'
extra_css:
    - jquery.fancybox.min.css
    - extra.css
extra_javascript:
    - jquery-3.5.0.slim.min.js
    - jquery.fancybox.min.js
    - extra.js
nav:
    - Documentation:
        - 'index.md'
        - 'faq.md'
        - 'MoorlFoundation/index.md'
        - 'MoorlFoundation/demo-assistant.md'
        - 'MoorlFoundation/listing.md'
        - 'MoorlFoundation/features-free.md'
        - 'MoorlFoundation/features-premium.md'
        - 'MoorlCreator/index.md'
        - 'MoorlGetTheLook/index.md'
        - 'MoorlMagazine/index.md'
        - 'MoorlForms/index.md'
        - 'MoorlFormsClassic/index.md'
        - 'MoorlFormsCustomProducts/index.md'
        - 'MoorlFormsCustomer/index.md'
        - 'MoorlFormsProduct/index.md'
        - 'MoorlFormsPopup/index.md'
        - 'MoorlFormsSlides/index.md'
        - 'MoorlStaging/index.md'
        - 'MoorlExtCat/index.md'
        - 'Moorl360DegreeViewer/index.md'
        - 'MoorlAccessoryFinder/index.md'
        - 'MoorlAutoLogout/index.md'
        - 'MoorlBankConnection/index.md'
        - 'MoorlDownloadCenter/index.md'
        - MoorlCms:
            - 'MoorlCmsBrandSlider/index.md'
            - 'MoorlCmsCtaBanner/index.md'
            - 'MoorlCmsDealCounter/index.md'
            - 'MoorlCmsFlipBox/index.md'
            - 'MoorlCmsInstagram/index.md'
            - 'MoorlCmsTestimonial/index.md'
            - 'MoorlCmsTwig/index.md'
            - 'MoorlShopTheLook/index.md'
            - 'MoorlFancyboxGallery/index.md'
        - 'MoorlCustomerAccounts/index.md'
        - MoorlFormBuilder:
            - 'MoorlFormBuilder/index.md'
            - 'MoorlFormBuilder/setup.md'
            - 'MoorlFormBuilder/user.md'
            - 'MoorlFormBuilder/mail_templates.md'
            - 'MoorlFormBuilder/elements.md'
            - 'MoorlFormBuilder/newsletter.md'
            - 'MoorlFormBuilder/events.md'
            - 'MoorlFormBuilder/interactive.md'
            - 'MoorlFormBuilder/faq.md'
            - Extensions:
                - 'MoorlFormRegistration/index.md'
                - 'MoorlFormCartExtend/index.md'
                - 'MoorlFormCartLineItem/index.md'
                - 'MoorlFormProductRequest/index.md'
        - 'MoorlInterrupter/index.md'
        - MoorlSignIn:
              - 'MoorlSignIn/index.md'
              - 'MoorlSignIn/facebook.md'
        - MoorlMerchantFinder:
              - 'MoorlMerchantFinder/index.md'
              - 'MoorlMerchantFinder/setup.md'
              - 'MoorlMerchantPicker/index.md'
        - 'MoorlProductAccessories/index.md'
        - 'MoorlProductConsultant/index.md'
        - 'MoorlProductPromo/index.md'
        - 'MoorlProductVideo/index.md'
    - Shopware Store: 'https://store.shopware.com/moori.html'
    - Shopware Demo Page: 'https://demo.moori.net/'
    - Imprint: 'https://moorleiche.com/impressum/'
