site_name: moori SW6 Plugin Docs
theme:
    name: 'material'
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          accent: light green
          primary: deep orange
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
plugins:
    - i18n:
          default_language: de
          languages:
              de: Deutsch
              en: English
              nl: Nederlands
          nav_translations:
              de:
                  Documentation: App Dokumentation
                  MoorlCms: Erlebniswelten CMS Apps
                  MoorlFormBuilder: Formular Baukasten
                  Extensions: Erweiterungen
                  MoorlSignIn: Login mit Facebook, Google usw
                  MoorlMagazine: Blog mit Wordpress Import
                  MoorlMerchantFinder: Händler- und Filialiensuche
                  Imprint: Impressum
              en:
                  Documentation: App Documentation
                  MoorlCms: Shopping worlds CMS Apps
                  MoorlFormBuilder: Form Builder
                  Extensions: Extensions
                  MoorlSignIn: Sign-In with Facebook, Google etc
                  MoorlMagazine: Blog with Wordpress Import
                  MoorlMerchantFinder: Merchant- and Storefinder
                  Imprint: Imprint
              nl:
                  Documentation: App Documentatie
                  Imprint: Afdruk

    - search
docs_dir: docs-source
site_dir: docs-html
site_url: 'https://docs.moori.net'
extra:
    consent:
        title: Cookie consent
        description: >
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
        cookies:
            matomo: Matomo Tracker
            custom: Disqus Board
    disqus: 'moori'
extra_css:
    - 'jquery.fancybox.min.css'
    - 'extra.css'
extra_javascript:
    - 'jquery-3.5.0.slim.min.js'
    - 'jquery.fancybox.min.js'
    - 'extra.js'


nav:
    - Documentation:
        - 'faq.md'
        - 'MoorlFoundation/index.md'
        - 'MoorlFoundation/demo-assistant.md'

        - 'Moorl360DegreeViewer/index.md'
        - 'MoorlAccessoryFinder/index.md'
        - 'MoorlAutoLogout/index.md'
        - 'MoorlBankConnection/index.md'
        - 'MoorlDownloadCenter/index.md'
        - MoorlCms:
            - 'MoorlCmsBrandSlider/index.md'
            - 'MoorlCmsCtaBanner/index.md'
            - 'MoorlCmsDealCounter/index.md'
            - 'MoorlCmsFlipBox/index.md'
            - 'MoorlCmsInstagram/index.md'
            - 'MoorlCmsTestimonial/index.md'
            - 'MoorlCmsTwig/index.md'
            - 'MoorlShopTheLook/index.md'
            - 'MoorlFancyboxGallery/index.md'
        - 'MoorlCustomerAccounts/index.md'
        - MoorlFormBuilder:
            - 'MoorlFormBuilder/index.md'
            - 'MoorlFormBuilder/setup.md'
            - 'MoorlFormBuilder/user.md'
            - 'MoorlFormBuilder/mail_templates.md'
            - 'MoorlFormBuilder/elements.md'
            - 'MoorlFormBuilder/newsletter.md'
            - 'MoorlFormBuilder/events.md'
            - 'MoorlFormBuilder/interactive.md'
            - 'MoorlFormBuilder/faq.md'
            - Extensions:
                - 'MoorlFormRegistration/index.md'
                - 'MoorlFormCartExtend/index.md'
                - 'MoorlFormCartLineItem/index.md'
                - 'MoorlFormProductRequest/index.md'
        - 'MoorlInterrupter/index.md'
        - MoorlSignIn:
              - 'MoorlSignIn/index.md'
              - 'MoorlSignIn/facebook.md'
        - MoorlMagazine:
              - 'MoorlMagazine/index.md'
              - 'MoorlMagazine/feed-api.md'
        - MoorlMerchantFinder:
              - 'MoorlMerchantFinder/index.md'
              - 'MoorlMerchantFinder/setup.md'
              - 'MoorlMerchantPicker/index.md'
        - 'MoorlProductAccessories/index.md'
        - 'MoorlProductConsultant/index.md'
        - 'MoorlProductPromo/index.md'
        - 'MoorlProductVideo/index.md'
        - 'MoorlRevSlider/index.md'
        - 'MoorlVideoCourse/index.md'

    - Shopware Store: 'https://store.shopware.com/moori.html'
    - Shopware Demo Page: 'https://demo.moori.net/'
    - Imprint: 'https://moorleiche.com/impressum/'
    - 'tags.md'
