site_name: Shopware 6 Plugin Dokumentation
copyright: >
  <a href="#__consent">Change cookie settings</a>
theme:
  name: 'material'
  custom_dir: docs-source/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: light green
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - tags:
      tags_file: tags.md
  - i18n:
      material_alternate: true
      default_language: de
      languages:
        de:
          name: Deutsch
          build: false
        en:
          name: English
          build: true
      nav_translations:
        en:
          Blog: Blog
          moori Plugin Dokumentation: moori Plugin Documentation
          Appflix Plugin Dokumentation: Appflix Plugin Documentation
          plugin/MoorlCms: Shopping worlds CMS Apps
          plugin/MoorlFormBuilder: Form Builder
          Extensions: Extensions
          plugin/MoorlSignIn: Sign-In with Facebook, Google etc
          plugin/MoorlMagazine: Blog with Wordpress Import
          plugin/MoorlMerchantFinder: Merchant- and Storefinder
          plugin/MoorlCreator: Public profiles
          Impressum: Imprint
  - search
docs_dir: 'docs-source'
site_dir: 'docs-html'
site_url: 'https://docs.moori.net'
extra:
  alternate:
    - name: Deutsch
      link: ./
      lang: de
      default: true
    - name: English
      link: ./en/
      lang: en
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      matomo: Matomo Analytics
    actions:
      - manage
      - accept
      - reject
extra_css:
  - jquery.fancybox.min.css
  - extra.css
extra_javascript:
  - jquery-3.5.0.slim.min.js
  - jquery.fancybox.min.js
  - extra.js
nav:
  - Home: index.md
  - moori Plugin Dokumentation:
      - 'plugin/index.md'
      - 'plugin/MoorlFoundation/index.md'
      - 'plugin/MoorlFoundation/demo-assistant.md'
      - 'plugin/MoorlFoundation/client.md'
      - 'plugin/MoorlFoundation/listing.md'
      - 'plugin/MoorlFoundation/advanced-search.md'
      - 'plugin/MoorlFoundation/features-free.md'
      - 'plugin/MoorlFoundation/features-premium.md'

      - 'plugin/MoorlCreator/index.md'
      - 'plugin/MoorlGetTheLook/index.md'
      - 'plugin/MoorlMagazine/index.md'

      - 'plugin/MoorlForms/index.md'
      - 'plugin/MoorlForms/how-tos.md'
      - 'plugin/MoorlFormsClassic/index.md'
      - 'plugin/MoorlFormsCustomProducts/index.md'
      - 'plugin/MoorlFormsCustomer/index.md'
      - 'plugin/MoorlFormsProduct/index.md'
      - 'plugin/MoorlFormsOrder/index.md'
      - 'plugin/MoorlFormsPopup/index.md'
      - 'plugin/MoorlFormsSlides/index.md'
      - 'plugin/MoorlForms/faq.md'
      - 'plugin/MoorlFormsHubspot/index.md'
      - 'plugin/MoorlFormsMautic/index.md'
      - 'plugin/MoorlFormsWebhook/index.md'
      - 'plugin/MoorlFormsCsv/index.md'

      - 'plugin/MoorlMerchantFinder/index.md'
      - 'plugin/MoorlMerchantPicker/index.md'

      - 'plugin/MoorlFormBuilder/index.md'
      - 'plugin/MoorlFormBuilder/setup.md'
      - 'plugin/MoorlFormBuilder/user.md'
      - 'plugin/MoorlFormBuilder/mail_templates.md'
      - 'plugin/MoorlFormBuilder/elements.md'
      - 'plugin/MoorlFormBuilder/newsletter.md'
      - 'plugin/MoorlFormBuilder/events.md'
      - 'plugin/MoorlFormBuilder/interactive.md'
      - 'plugin/MoorlFormBuilder/faq.md'

      - 'plugin/MoorlCmsBrandSlider/index.md'
      - 'plugin/MoorlCmsCtaBanner/index.md'
      - 'plugin/MoorlCmsFlipBox/index.md'
      - 'plugin/MoorlCmsTestimonial/index.md'
      - 'plugin/MoorlCmsTwig/index.md'
      - 'plugin/MoorlShopTheLook/index.md'
      - 'plugin/MoorlFancyboxGallery/index.md'
      - 'plugin/MoorlCmsCategoryListing/index.md'

      - 'plugin/MoorlStaging/index.md'
      - 'plugin/MoorlExtCat/index.md'
      - 'plugin/Moorl360DegreeViewer/index.md'
      - 'plugin/MoorlAccessoryFinder/index.md'
      - 'plugin/MoorlAutoLogout/index.md'
      - 'plugin/MoorlBankConnection/index.md'
      - 'plugin/MoorlDownloadCenter/index.md'
      - 'plugin/MoorlCustomerAccounts/index.md'
      - 'plugin/MoorlInterrupter/index.md'
      - 'plugin/MoorlSignIn/index.md'
      - 'plugin/MoorlProductAccessories/index.md'
      - 'plugin/MoorlProductConsultant/index.md'
      - 'plugin/MoorlProductPromo/index.md'
      - 'plugin/MoorlProductVideo/index.md'
  - Appflix Plugin Dokumentation:
      - 'appflix/index.md'
      - 'appflix/AppflixDewaShop/index.md'
      - 'appflix/AppflixStudygood/index.md'
      - 'appflix/AppflixCustomerMarket/index.md'
      - 'appflix/AppflixMultiPdf/index.md'
  - Shopware Store: 'https://store.shopware.com/moori.html'
  - Demo Shop: 'https://demo.moori.net/'
  - Impressum: 'https://moorleiche.com/impressum/'
