site_name: moori - Shopware 6 Plugin Dokumentation
repo_url: https://github.com/moorl/documentation-moorl-sw6
edit_uri: blob/master/docs-source/
theme:
    name: 'material'
docs_dir: docs-source
site_dir: docs-html
extra_css:
    - 'extra.css'
extra_javascript:
nav:
    - Home: 'index.md'
    - Häufig gestellte Fragen (FAQ): faq.md
    - Foundation / Basis Plugin: foundation.md
    - Händler- und Filialensuche:
        - Allgemeines: MoorlMerchantFinder/index.md
        - Add-On - Händlerauswahl: MoorlMerchantPicker/index.md
    - Formular Baukasten:
        - Allgemeines: MoorlFormBuilder/index.md
        - Setup Guide: MoorlFormBuilder/setup.md
        - User Guide: MoorlFormBuilder/user.md

    - Shopware Store: 'https://store.shopware.com/moori.html'
    - Kontakt: 'mailto:info@moorleiche.com'
    - Impressum: 'https://moorleiche.com/impressum/'
