name: Build & Deploy MkDocs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs-source/**'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs + Plugins
        run: |
          pip install --upgrade pip
          pip install mkdocs-material mkdocs-static-i18n
          # optional, aber oft hilfreich:
          pip install mkdocs-minify-plugin
          pip install pillow cairosvg

      - name: Build site
        run: mkdocs build --strict

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-html   # entspricht deinem site_dir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
